### ISSUE TITLE
Failed to build executable!

### ISSUE THREAD

**Issue by ghost** [geode-lang/geode#28]
@mewmew @fossabot @nickwanninger 

```
[fatal] failed to run command `clang --std=c99 -lm -lc -lgc -pthread -DREDIRECT_MALLOC=xmalloc -DIGNORE_FREE /Users/g/.geode/build/usr/local/lib/geodelib/io/io.o /Users/g/.geode/build/usr/local/lib/geodelib/mem/mem.o /Users/g/.geode/build/usr/local/lib/geodelib/runtime/runtime.o /Users/g/.geode/build/usr/local/lib/geodelib/runtime/xmalloc.o /Users/g/.geode/build/Users/g/Desktop/geode-master/bin/file.ll -o /Users/g/.geode/build/a.out`: `exit status 1`

/Usersg/.geode/build/Users/g/Desktop/geode-master/bin/file.ll:16:54: error: expected value token
        %0 = call i8* @raw_copy(i8* getelementptr ([14 x i8], [14 x i8]* @.str.0, i32 0, i32 0), i32 14)
                                                            ^
1 error generated.
```

Failed to build executable from `hello_world.g`:

```
is main
include "io"

func main int {
        io:print("Hello, world\n");
        return 0;
}
```

**OS:** macOS
**Arch:** x86_64

**Command:**

> ./geode build hello_world.g

**Comment by nickwanninger** [comment]
Come on, whats up with the spam?

Unfortunately I am not working on this project anymore, and am not sure I can help you with the bug you are having. It looks like a possible LLVM syntax change that I am not interested in fixing.

Next time you need someone's attention, don't spam a button hoping an email storm will get you that attention.

**Comment by mewmew** [comment]
I also don't know the exact cause of the issue. @nickwanninger, feel free to freeze this issue to prevent spam, I'm also not a fan.
